steps:
  # ========================================
  # BACKEND
  # ========================================
  - name: "gcr.io/cloud-builders/docker"
    id: build-backend
    args:
      - "build"
      - "-t"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME"
      - "--build-arg"
      - "COMMIT_SHA=$COMMIT_SHA"
      - "."

  - name: "gcr.io/cloud-builders/docker"
    id: push-backend
    args:
      - "push"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME"

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-backend-staging
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "adn-app"
      - "--image"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME"
      - "--region"
      - "$_REGION"
      - "--project"
      - "$_STAGING_PROJECT_ID"

  # ========================================
  # FRONTEND
  # ========================================
  - name: "gcr.io/cloud-builders/gcloud"
    id: get-backend-url
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        BACKEND_URL=$$(gcloud run services describe adn-app \
          --region $_REGION \
          --project $_STAGING_PROJECT_ID \
          --format="value(status.url)")
        echo "$$BACKEND_URL" > backend_url.txt
        echo "Backend URL: $$BACKEND_URL"

  - name: "gcr.io/cloud-builders/docker"
    id: build-frontend
    waitFor: ['get-backend-url']
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        BACKEND_URL=$$(cat backend_url.txt)
        echo "Building frontend with API: $$BACKEND_URL"
        
        docker build \
          --build-arg NEXT_PUBLIC_API_URL=$$BACKEND_URL \
          -t $_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME-frontend \
          -f frontend/Dockerfile \
          frontend/

  - name: "gcr.io/cloud-builders/docker"
    id: push-frontend
    args:
      - "push"
      - "$_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME-frontend"

  - name: "gcr.io/cloud-builders/gcloud"
    id: deploy-frontend-staging
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        BACKEND_URL=$$(cat backend_url.txt)
        
        gcloud run deploy adn-app-frontend \
          --image $_REGION-docker.pkg.dev/$PROJECT_ID/$_ARTIFACT_REGISTRY_REPO_NAME/$_CONTAINER_NAME-frontend \
          --region $_REGION \
          --project $_STAGING_PROJECT_ID \
          --set-env-vars NEXT_PUBLIC_API_URL=$$BACKEND_URL \
          --allow-unauthenticated

  # ========================================
  # TESTS
  # ========================================
  - name: "gcr.io/cloud-builders/gcloud"
    id: fetch-staging-url
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $$(gcloud run services describe adn-app-frontend \
        --region $_REGION --project $_STAGING_PROJECT_ID --format="value(status.url)") > staging_url.txt

  - name: gcr.io/cloud-builders/gcloud
    id: fetch-id-token
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo $$(gcloud auth print-identity-token -q) > id_token.txt

  # - name: "python:3.12-slim"
  #   id: load_test
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       export _ID_TOKEN=$$(cat id_token.txt)
  #       export _STAGING_URL=$$(cat staging_url.txt)
  #       pip install locust==2.31.1 --user
  #       locust -f tests/load_test/load_test.py \
  #       --headless \
  #       -H $$_STAGING_URL \
  #       -t 30s -u 10 -r 0.5 \
  #       --csv=tests/load_test/.results/results \
  #       --html=tests/load_test/.results/report.html
  #   env:
  #     - 'PATH=/usr/local/bin:/usr/bin:~/.local/bin'

  # - name: gcr.io/cloud-builders/gcloud
  #   id: export-results-to-gcs
  #   entrypoint: /bin/bash
  #   args:
  #     - "-c"
  #     - |
  #       export _TIMESTAMP=$$(date +%Y%m%d-%H%M%S)
  #       gsutil -m cp -r tests/load_test/.results gs://$_BUCKET_NAME_LOAD_TEST_RESULTS/results-$$_TIMESTAMP
  #       echo "_________________________________________________________________________"
  #       echo "Load test results: gs://$_BUCKET_NAME_LOAD_TEST_RESULTS/results-$$_TIMESTAMP"
  #       echo "_________________________________________________________________________"

  - name: gcr.io/cloud-builders/gcloud
    id: trigger-prod-deployment
    entrypoint: gcloud
    args:
      - "beta"
      - "builds"
      - "triggers"
      - "run"
      - "deploy-adn-app"
      - "--region"
      - "$LOCATION"
      - "--project"
      - "$PROJECT_ID"
      - "--sha"
      - $COMMIT_SHA

  - name: gcr.io/cloud-builders/gcloud
    id: echo-view-build-trigger-link
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        echo "_________________________________________________________________________"
        echo "Production deployment triggered"
        echo "https://console.cloud.google.com/cloud-build/builds;region=$LOCATION"
        echo "_________________________________________________________________________"

substitutions:
  _STAGING_PROJECT_ID: YOUR_STAGING_PROJECT_ID
  _REGION: europe-west1

logsBucket: gs://${PROJECT_ID}-adn-app-logs/build-logs
options:
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET